FROM leerssej/tidycosmos
RUN install2.r --error \
    --deps TRUE \
    reshape2 \
    lazyeval \
    MatchIt \
    rpart \
    car \
    compute.es \
    effects \
    multcomp \
    pastecs \
    HH \
    mlbench \
    mice \
    VIM \
    lattice \
    optimx \
    lme4 
    