# Library catalog for dr_shontocker
library(reshape)
library(lazyeval)
library(MatchIt)
library(rpart)
library(car)
library(compute.es)
library(effects)
library(multcomp)
library(pastecs)
library(HH)
library(mlbench)
library(mice)
library(VIM)
library(lattice)
library(optimx)
library(lm)
