FROM rocker/tidyverse

RUN install2.r --error \
    --deps TRUE \
    cowplot \
    skimr \
    visdat \
    viridis \
    zoo \
    RODBC \
    keyringr \
    stringdist \
    googlesheets \
    broom \
    readxl \
    magrittr \
    lubridate \
    remotes